
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SCIS2-08
 */
public class Ventanaprincipal extends javax.swing.JFrame {

    int [] arrayMenores;
    int [] arrayMayores;
    int [] arrayAdultos;
    
    public Ventanaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("SISTEMA ACADEMICO");

        create.setText("Crear");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        search.setText("Consultar");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(create)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(search))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        arrayMenores = new int[5];
        arrayMayores = new int[5];
        arrayAdultos = new int[5];
        int person = 1; int ime = 0; int ima = 0; int iad = 0;
        
        while(person <= 15){
            
            int age = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Diga su edad"));

            if(age < 18 && age > 0 ){
                if(ime < arrayMenores.length){
                    JOptionPane.showMessageDialog(rootPane, "Usted es menor de edad");
                    arrayMenores[ime] = age;
                    ime++;
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se aceptan mas menores de edad");
                    person--;
                }

            }else if(age < 60 && age >= 18){
                if(ima < arrayMayores.length){
                    JOptionPane.showMessageDialog(rootPane, "Usted es mayor de edad");
                    arrayMayores[ima] = age;
                    ima++;
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se aceptan mas mayores de edad");
                    person--;
                }

            }else if(age >= 60){
                if(iad < arrayAdultos.length){
                    JOptionPane.showMessageDialog(rootPane, "Usted es adulto mayor");
                    arrayAdultos[iad] = age;
                    iad++;
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se aceptan mas adultos mayores");
                    person--;
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Edad no valida");
            }
            
            person++;
        }
      
    }//GEN-LAST:event_createActionPerformed

    //Metodo para concatenar 
    private String arrayToString(int[] array){
        String concatenate = "";
        for(int i = 0; i < array.length; i++){
            concatenate += array[i] + "\n";
        }
        return concatenate;
    }
    
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        //Para mostrar las edades de menor a mayor 
        //Es un metodo de java que hace que el contenido de los array de ordene
        Arrays.sort(arrayMenores);
        Arrays.sort(arrayMayores);    
        Arrays.sort(arrayAdultos);
        
        JOptionPane.showMessageDialog(rootPane, "Menores de edad");
        JOptionPane.showMessageDialog(rootPane,arrayToString(arrayMenores));
        JOptionPane.showMessageDialog(rootPane, "Mayores de edad");
        JOptionPane.showMessageDialog(rootPane, arrayToString(arrayMayores));
        JOptionPane.showMessageDialog(rootPane, "Adulto mayor");
        JOptionPane.showMessageDialog(rootPane, arrayToString(arrayAdultos));
    }//GEN-LAST:event_searchActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
